require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MercadosController do

  # This should return the minimal set of attributes required to create a valid
  # Mercado. As you add validations to Mercado, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MercadosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all mercados as @mercados" do
      mercado = Mercado.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mercados).should eq([mercado])
    end
  end

  describe "GET show" do
    it "assigns the requested mercado as @mercado" do
      mercado = Mercado.create! valid_attributes
      get :show, {:id => mercado.to_param}, valid_session
      assigns(:mercado).should eq(mercado)
    end
  end

  describe "GET new" do
    it "assigns a new mercado as @mercado" do
      get :new, {}, valid_session
      assigns(:mercado).should be_a_new(Mercado)
    end
  end

  describe "GET edit" do
    it "assigns the requested mercado as @mercado" do
      mercado = Mercado.create! valid_attributes
      get :edit, {:id => mercado.to_param}, valid_session
      assigns(:mercado).should eq(mercado)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mercado" do
        expect {
          post :create, {:mercado => valid_attributes}, valid_session
        }.to change(Mercado, :count).by(1)
      end

      it "assigns a newly created mercado as @mercado" do
        post :create, {:mercado => valid_attributes}, valid_session
        assigns(:mercado).should be_a(Mercado)
        assigns(:mercado).should be_persisted
      end

      it "redirects to the created mercado" do
        post :create, {:mercado => valid_attributes}, valid_session
        response.should redirect_to(Mercado.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mercado as @mercado" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mercado.any_instance.stub(:save).and_return(false)
        post :create, {:mercado => {}}, valid_session
        assigns(:mercado).should be_a_new(Mercado)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mercado.any_instance.stub(:save).and_return(false)
        post :create, {:mercado => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mercado" do
        mercado = Mercado.create! valid_attributes
        # Assuming there are no other mercados in the database, this
        # specifies that the Mercado created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mercado.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => mercado.to_param, :mercado => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested mercado as @mercado" do
        mercado = Mercado.create! valid_attributes
        put :update, {:id => mercado.to_param, :mercado => valid_attributes}, valid_session
        assigns(:mercado).should eq(mercado)
      end

      it "redirects to the mercado" do
        mercado = Mercado.create! valid_attributes
        put :update, {:id => mercado.to_param, :mercado => valid_attributes}, valid_session
        response.should redirect_to(mercado)
      end
    end

    describe "with invalid params" do
      it "assigns the mercado as @mercado" do
        mercado = Mercado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mercado.any_instance.stub(:save).and_return(false)
        put :update, {:id => mercado.to_param, :mercado => {}}, valid_session
        assigns(:mercado).should eq(mercado)
      end

      it "re-renders the 'edit' template" do
        mercado = Mercado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mercado.any_instance.stub(:save).and_return(false)
        put :update, {:id => mercado.to_param, :mercado => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mercado" do
      mercado = Mercado.create! valid_attributes
      expect {
        delete :destroy, {:id => mercado.to_param}, valid_session
      }.to change(Mercado, :count).by(-1)
    end

    it "redirects to the mercados list" do
      mercado = Mercado.create! valid_attributes
      delete :destroy, {:id => mercado.to_param}, valid_session
      response.should redirect_to(mercados_url)
    end
  end

end
